apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: knative
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/knative/operator/releases/download/knative-v1.3.1/operator.yaml