---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: knative-serving
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/knative-serving
  prune: true
  TargetNamespace: knative-serving
  dependsOn:
    - name: knative-operator